sudo: required
language: bash
services:
- docker
env:
  global:
    secure: Ujw7Kb9s//AwlvuPDfyVGl9TdVw1D0qVTpBSIY58xOXu2h3/23a0fi88s2rUv7IIu6z14phoihrCyYEgF1hrzk2NZJ/lsBugkNJzPqeAHu3vU7gJhgxEHQZ+YQkWUBCSXIVbxBnLXllkN1SvccBzGTKCZ/ab5pU4PqZrbI/cYbX3Htd8/AZrvQ5H5a1mx6xlCgz1FU6SrXZ1U0YnRCIY0s6Z8jeS93kE5iPhHUcqMiT0uXZp9KvNbPGSHIfn7OabTSjM4nkKYO1BTsGMJXUPfsBGAgyv8I7UWFFfIouSwGRyH5eH//3vpEFjQWI7Qt+vajrlKK5FdTZZs9zhj1D5JK4eXNHoSnzrj2u5Ju7RAgc9ldrRmzinkA2SqLff7gP/xt0FeQXWQxEvYmU/f64m+bxVh94+eqQMsKo471oV/TDayP/vWcw0w6rTLpbyMIlDgZNrom5QKvFTNwVTuIkNmXQTZrOm7EEGJqh4+WAoB36Ffvnsu8P3ONLxo9h3hp6xgt/7vHlpgQP1TxdmYi9NCcMwRzUcl5VSe/Bbn3jmMRQskFMrGJrC/U3dsiAxI/uZ//zFxCErin6QR+FMs5tbMKSWjwsJ2azD02cqrucKAk+Goiqlnmd0JBWFVXcocnKvO800EjlNVWQcgrDWG1AS5wo2OOigQWqhoTN1z+mKAD4=
  matrix:
  - ARCH=armhf
  - ARCH=aarch64
  - ARCH=amd64
  - ARCH=armel
before_install:
- curl -L https://goss.rocks/install | sudo sh
- sudo apt-get -y install qemu-user-static
- docker run --rm --privileged multiarch/qemu-user-static:register
script:
- docker build -f Dockerfile_debian_$ARCH -t visibilityspots/pi-hole:$ARCH ./
- docker run --name pi-hole --rm -ti --entrypoint='' visibilityspots/pi-hole:$ARCH
  pihole -v
- dgoss run --name pi-hole -ti visibilityspots/pi-hole:$ARCH
after_success:
- docker login -u=visibilityspots -p="$DOCKER_PASSWORD"; docker push visibilityspots/pi-hole:$ARCH
