sudo: required
language: bash
services:
- docker

env:
  global:
    secure: Or5wtPms5rI3oMEGSuzcbA5bYB6yTCnKslihKsjFyldkVBrEz0htBDUZto78HxWblMjHypR1YRCxhoToFKI1a0Q5HvnD7gbrDgJDxZmXN0LpHxS3hubMYfYc6V/DALYY29u2Foq4aoBsBMKC22fwBODFkzwtaIY/KRYxP2LDQHfBYZBMxd6eBIu8jG5UhuCVgU2gz7/0XaIouoHCBNqacf8dgv+635IjyEZATGhuAJ6TOFtaXwyf588xc5jFCoKlo2c3cCu9dHtzAsrG9kk5mgFmZkxpQkuQVTb8n8I6bekuaW0Si6xFSLRRZcbEo8aUPF6PmHT42RcXj/R56HlyYJxX32+ZVSTaftrQ0330KPIzSG8WFDvt0rCa0PUKJvWd1UcB+8ZRCVCxZse1p0IlaeYDZu9D0EvyZowY1nemFuFTU52g2tWYtLoQVGJ43fATBUNxunulg0/i55ZzHDFlE4XS1P2Scsoqp42UVbdCieotT7rhNJwL1jdxgEJfh958wpFVnoC5RTl6w5tuFe/cM+X7TsDT6EuyrMr0hMgW5cLfJ3Q4meYA0LE2GSyELxNRWGUdwCA4h4tyeCigdRHXb1UXnh969O0ehI4N3ADy9ssO2TkvyfkajCVh+6hPXC8OFPO/uPyjc1zCpaGVvtJS2hMOdyJ9obm8JiskeCGP8t8=
  matrix:
    - ARCH=armhf
    - ARCH=aarch64
    - ARCH=amd64
    - ARCH=armel

before_install:
  - curl -L https://goss.rocks/install | sudo sh
  - sudo apt-get -y install qemu-user-static
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - docker build -f Dockerfile_debian_$ARCH -t visibilityspots/pi-hole:$ARCH ./
  - dgoss run --name pi-hole -ti visibilityspots/pi-hole:$ARCH

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u=visibilityspots -p="$DOCKER_PASSWORD"; docker push visibilityspots/pi-hole:$ARCH; fi
